### ISSUE TITLE
Outline and todo list

### ISSUE THREAD

**Issue by tima101** [async-labs/async-saas#1]
- [ ] Initial boilerplate and project structure

- [ ] Add TypeScript
- [ ] Add MobX
- [ ] Dashboard, Settings pages

External APIs:
- [ ] Google OAuth
- [ ] AWS SES
- [ ] Mailchimp
- [ ] Stripe (manage subscriptions, manage card, invoices/history)

Tech bits:
- forked process in Node
- server-side caching
- lazy load with SSR/CSR
- setting user prop with MobX
- separate Next (client) and Express (APIs and sockets) servers 

Candidate features:
- basic analytics
- team, invite member, manager
- deployment guide

**Comment by adamburmister** [comment]
What are your plans around implementing Stripe subs? Will you be implementing Usage Records (https://stripe.com/docs/api#usage_records) – they'd be useful for a wide class of SaaS apps.

**Comment by tima101** [comment]
I am locking this issue since this is my internal TODO list.
